from textwrap import dedent

import pytest

from aoc_2024 import day_08


@pytest.fixture
def puzzle_input() -> str:
    return dedent(
        """\
        ............
        ........0...
        .....0......
        .......0....
        ....0.......
        ......A.....
        ............
        ............
        ........A...
        .........A..
        ............
        ............
        """
    )


def test_solve_a(puzzle_input: str):
    assert day_08.solve_a(puzzle_input) == 14


def test_solve_b(puzzle_input: str):
    assert day_08.solve_b(puzzle_input) == 34
